BiocManager::install("ShortRead")
library(ShortRead)
df<-readFastq("CTRL_1_R1.fastq")
View(df)
sread(reverseComplement(rfq))
quality(reverseComplement(rfq))
quality(trimTails(rfq, 2, "H", successive=TRUE))
